"""Scope login lockouts to account and source IP

Revision ID: 20b5ca11de84
Revises: 48dfd3e9c4dc
Create Date: 2026-09-01 04:16:48.137989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20b5ca11de84'
down_revision: Union[str, Sequence[str], None] = '48dfd3e9c4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_lockouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ip_address', name='uq_login_lockouts_user_ip')
    )
    op.create_index(op.f('ix_login_lockouts_user_id'), 'login_lockouts', ['user_id'], unique=False)
    op.drop_column('users', 'failed_login_count')
    op.drop_column('users', 'locked_until')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locked_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # server_default added (autogenerate didn't include one): NOT NULL with no
    # default fails outright on a non-empty users table -- every existing row
    # would violate the constraint the instant it's added.
    op.add_column(
        'users',
        sa.Column('failed_login_count', sa.INTEGER(), server_default='0', autoincrement=False, nullable=False),
    )
    op.drop_index(op.f('ix_login_lockouts_user_id'), table_name='login_lockouts')
    op.drop_table('login_lockouts')
    # ### end Alembic commands ###
